server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://config-server:8888/"

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true # Permet de trouver les services via Eureka automatiquement
      #      Gestion des Cross Origin Ressource Sharing (CORS)
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000" #[OPTIONS] http://localhost:8080/api/users qui doit etre permis.
            allowedMethods: [ "GET","POST","PUT","OPTIONS" ]
            allowedHeaders: "*"
      #      Gestion des Routes ------------
      routes:
        #        - Routes correspondants au user-service ----
        #        les requetes api/users/** ->(seront redirige vers) user-service en appelant le load balancer via Eureka
        # ----- user-service-----------
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0
            #            Gestion de la limitation de debit
            - name: RequestRateLimiter
              args:
                replenishRate: 5
                burstCapacity: 10
                keyResolver: "#{@userKeyResolver}"
        #-------- ticket-service----------
        - id: ticket-service
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/api/tickets/**
          filters:
            - StripPrefix=0
            - name: RequestRateLimiter
              args:
                replenishRate: 5
                burstCapacity: 10
                keyResolver: "#{@userKeyResolver}"
        #-------- notification-service----------
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=0
            - name: RequestRateLimiter
              args:
                replenishRate: 5
                burstCapacity: 10
                keyResolver: "#{@userKeyResolver}"
        #-------- document-service----------
        - id: document-service
          uri: lb://DOCUMENT-SERVICE
          predicates:
            - Path=/api/documents/**
          filters:
            - StripPrefix=0
            - name: RequestRateLimiter
              args:
                replenishRate: 5
                burstCapacity: 10
                keyResolver: "#{@userKeyResolver}

springdoc:
  swagger-ui:
    # Permet de classer les docs par service dans le dropdown
    urls:
      - name: API Gateway (TicketFlow)
        url: /v3/api-docs
      - name: User Service
        url: /user-service/v3/api-docs
      - name: Ticket Service
        url: /ticket-service/v3/api-docs
      - name: Document Service
        url: /document-service/v3/api-docs
      - name: Notification Service
        url: /notification-service/v3/api-docs
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  tracing:
    enabled: false