server:
  port: 8080

spring:
  application:
    name: gateway-service

  config:
    import: "optional:configserver:http://config-server:8888/"


springdoc:
  swagger-ui:
    # Permet de classer les docs par service dans le dropdown
    path: /swagger-ui.html
    urls:
      - name: API Gateway (TicketFlow)
        url: gateway-service/v3/api-docs
      - name: User Service
        url: /api/users/v3/api-docs
      - name: Ticket Service
        url: /api/tickets/v3/api-docs
      - name: Document Service
        url: /api/documents/v3/api-docs
      - name: Notification Service
        url: /api/notifications/v3/api-docs
  api-docs:
    enabled: true
    path: /v3/api-docs