spring:
  application:
    name: user-service

  config:
    import: "optional:configserver:http://localhost:8888"

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false # Pour simplifier la lecture par les autres services