server:
  port: 8888


spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file:/app/config-repo
          add-label-location: false
#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
logging:
  level:
    org.springframework.cloud.config: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
  tracing:
    sampling:
      probability: 1.0  # Envoie 100% des traces (pour le dev/test)
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"